# Generated by Django 3.2.4 on 2021-09-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_uhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
