# Generated by Django 3.2.4 on 2021-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('lmobile', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('tloan', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
