# Generated by Django 3.2.7 on 2021-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_loanapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='uhistory',
            name='histype',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
